apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: ngumonelson123/account-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: vault-secrets
              key: POSTGRES_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: vault-secrets
              key: POSTGRES_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: vault-secrets
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: ClusterIP
  selector:
    app: account
  ports:
  - port: 8000
    targetPort: 8000
