apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: api-gateway
        image: ngumonelson123/api-gateway:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: ACCOUNT_URL
          value: "http://account-service:8000"
        - name: LOAN_URL
          value: "http://loan-service:7000"
