apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secret
  namespace: default
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: vault-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_HOST
    remoteRef:
      key: database
      property: host
  - secretKey: POSTGRES_USER
    remoteRef:
      key: database
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: database
      property: password