apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: vault-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_HOST
    remoteRef:
      key: finops/database
      property: host
  - secretKey: POSTGRES_USER
    remoteRef:
      key: finops/database
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: finops/database
      property: password
